wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.15
    start_time: 1671506392.308108
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.9.15
      5: 0.13.7
      8:
      - 2
      - 5
created_at:
  desc: null
  value: '2022-12-20T00:20:14'
fine_tuned_model:
  desc: null
  value: curie:ft-personal:donamail-2022-12-19-23-30-35
hyperparams:
  desc: null
  value:
    batch_size: 32
    learning_rate_multiplier: 0.1
    n_epochs: 1
    prompt_loss_weight: 0.01
id:
  desc: null
  value: ft-hhQQjZcdxPOMiLcV8A3X01xT
model:
  desc: null
  value: curie
n_train:
  desc: null
  value: 3892
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-LHQ1hO4HFoUnL8EXVtcSdppO
result_files:
  desc: null
  value:
    bytes: 6160
    created_at: 1671492636
    filename: compiled_results.csv
    id: file-ffxxqgLeHpgET4NXbkLU6mMb
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 13405886
    created_at: 1671489081
    filename: data_prepared.jsonl
    id: file-Z9sNnrI93EeGedhKZFPwRi4p
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1671492636
validation_files:
  desc: null
  value: []
